CREATE OR REPLACE FUNCTION fibonaci(n INTEGER) RETURNS INTEGER AS $$
DECLARE
f1 INTEGER=0;
f2 INTEGER=1;
f3 INTEGER;
BEGIN
RAISE NOTICE '%', f1;
RAISE NOTICE '%', f2;
FOR i IN 3..n
LOOP
f3:=f2+f1;
f1:=f2;
f2:=f3;
RAISE NOTICE '%', f2;
END LOOP;
END;
$$ LANGUAGE PLPGSQL;
SELECT fibonaci(20);
